import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { ClerkProvider } from "@clerk/nextjs";
import { ClerkHeader } from "@/components/auth/ClerkHeader";
import { SyncClerkUser } from "@/components/auth/SyncClerkUser";
import "../styles/globals.css";

const tasaOrbiter = localFont({
  variable: "--font-geist-sans",
  display: "swap",
  adjustFontFallback: false,
  src: [
    {
      path: "../assets/fonts/TASA_Orbiter/static/TASAOrbiter-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/TASA_Orbiter/static/TASAOrbiter-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/TASA_Orbiter/static/TASAOrbiter-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/TASA_Orbiter/static/TASAOrbiter-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/TASA_Orbiter/static/TASAOrbiter-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${tasaOrbiter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <SyncClerkUser />
          <ClerkHeader />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
